[package]
name = "generate-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.136"
solana-client = "2.1.9"
solana-sdk = "2.1.9"
